/* Auto-generated from Pravopisanie_pristavok_36_variantov_2023.pdf */

export interface PrefixItem {
  display: string;
  correct: string;
  wrong: string;
}

export type PrefixCategory = 'unchanged' | 'preEpri' | 'zs' | 'iy' | 'yer' | 'mixed';

export const PREFIX_CATEGORY_LABELS: Record<Exclude<PrefixCategory, 'mixed'> | 'mixed', string> = {
  unchanged: 'Неизменяемые приставки и РАЗ-/РОС-',
  preEpri:   'Приставки ПРЕ- и ПРИ-',
  zs:        '-З/-С на конце приставок, приставка С-',
  iy:        'И/Ы после приставок',
  yer:       'Разделительные Ъ и Ь',
  mixed:     'Смешанный',
};

export const PREFIX_DATA: Record<Exclude<PrefixCategory, 'mixed'>, PrefixItem[]> = {
  unchanged: [
    { display: 'без..тказный', correct: 'безотказный', wrong: 'безатказный' },
    { display: 'вз..браться', correct: 'взобраться', wrong: 'взабраться' },
    { display: 'воз..мнить', correct: 'возомнить', wrong: 'возамнить' },
    { display: 'в..скликнул', correct: 'воскликнул', wrong: 'васкликнул' },
    { display: 'дерево..брабатывающий', correct: 'деревообрабатывающий', wrong: 'деревоабрабатывающий' },
    { display: 'д..бела', correct: 'добела', wrong: 'дабела' },
    { display: 'д..гнать', correct: 'догнать', wrong: 'дагнать' },
    { display: 'з..вязать', correct: 'завязать', wrong: 'зовязать' },
    { display: 'запр..кинуть', correct: 'запрокинуть', wrong: 'запракинуть' },
    { display: 'н..право', correct: 'направо', wrong: 'ноправо' },
    { display: 'нед..варить', correct: 'недоварить', wrong: 'недаварить' },
    { display: 'нед..верие', correct: 'недоверие', wrong: 'недаверие' },
    { display: 'нед..стача', correct: 'недостача', wrong: 'недастача' },
    { display: 'нед..считаться', correct: 'недосчитаться', wrong: 'недасчитаться' },
    { display: 'нен..рушаемый', correct: 'ненарушаемый', wrong: 'ненорушаемый' },
    { display: 'не..бнесённый', correct: 'необнесённый', wrong: 'неабнесённый' },
    { display: 'необ..зримый', correct: 'необозримый', wrong: 'необазримый' },
    { display: 'не..хватный', correct: 'неохватный', wrong: 'неахватный' },
    { display: 'непр..будный', correct: 'непробудный', wrong: 'непрабудный' },
    { display: 'об..грев', correct: 'обогрев', wrong: 'обагрев' },
    { display: 'об..млеть', correct: 'обомлеть', wrong: 'обамлеть' },
    { display: 'от..бравший', correct: 'отобравший', wrong: 'отабравший' },
    { display: 'от..рвать', correct: 'оторвать', wrong: 'отарвать' },
    { display: 'п..дниматься', correct: 'подниматься', wrong: 'падниматься' },
    { display: 'п..дножие', correct: 'подножие', wrong: 'падножие' },
    { display: 'под..брать', correct: 'подобрать', wrong: 'подабрать' },
    { display: 'под..двинуть', correct: 'пододвинуть', wrong: 'подадвинуть' },
    { display: 'под..звать', correct: 'подозвать', wrong: 'подазвать' },
    { display: 'под..йти', correct: 'подойти', wrong: 'подайти' },
    { display: 'под..слать', correct: 'подослать', wrong: 'подаслать' },
    { display: 'п..завчера', correct: 'позавчера', wrong: 'пазавчера' },
    { display: 'поз..вчера', correct: 'позавчера', wrong: 'позовчера' },
    { display: 'поз..горать', correct: 'позагорать', wrong: 'позогорать' },
    { display: 'поз..прошлый', correct: 'позапрошлый', wrong: 'позопрошлый' },
    { display: 'поз..растать', correct: 'позарастать', wrong: 'позорастать' },
    { display: 'п..знавательный', correct: 'познавательный', wrong: 'пазнавательный' },
    { display: 'п..знавать', correct: 'познавать', wrong: 'пазнавать' },
    { display: 'п..никнуть', correct: 'поникнуть', wrong: 'паникнуть' },
    { display: 'п..одаль', correct: 'поодаль', wrong: 'паодаль' },
    { display: 'пор..ссуждать', correct: 'порассуждать', wrong: 'пороссуждать' },
    { display: 'пр..бабушка', correct: 'прабабушка', wrong: 'пробабушка' },
    { display: 'пр..дедушка', correct: 'прадедушка', wrong: 'продедушка' },
    { display: 'пр..родина', correct: 'прародина', wrong: 'прородина' },
    { display: 'пр..славяне', correct: 'праславяне', wrong: 'прославяне' },
    { display: 'пр..язык', correct: 'праязык', wrong: 'проязык' },
    { display: 'преп..давать', correct: 'преподавать', wrong: 'препадавать' },
    { display: 'р..зводить', correct: 'разводить', wrong: 'розводить' },
    { display: 'раз..гнаться', correct: 'разогнаться', wrong: 'разагнаться' },
    { display: 'раз..чаровать', correct: 'разочаровать', wrong: 'разачаровать' },
    { display: 'р..зыскать', correct: 'разыскать', wrong: 'розыскать' },
    { display: 'р..списные', correct: 'расписные', wrong: 'росписные' },
    { display: 'расп..ложить', correct: 'расположить', wrong: 'распаложить' },
    { display: 'р..спорядок', correct: 'распорядок', wrong: 'роспорядок' },
    { display: 'с..автор', correct: 'соавтор', wrong: 'саавтор' },
    { display: 'с..звучие', correct: 'созвучие', wrong: 'сазвучие' },
    { display: 'с..звучный', correct: 'созвучный', wrong: 'сазвучный' },
    { display: 'с..подчинение', correct: 'соподчинение', wrong: 'саподчинение' },
  ],
  preEpri: [
    { display: 'беспр..кословно', correct: 'беспрекословно', wrong: 'бесприкословно' },
    { display: 'беспр..страстный', correct: 'беспристрастный', wrong: 'беспрестрастный' },
    { display: 'гостепр..имный', correct: 'гостеприимный', wrong: 'гостепреимный' },
    { display: 'непр..взойдённый', correct: 'непревзойдённый', wrong: 'непривзойдённый' },
    { display: 'непр..менно', correct: 'непременно', wrong: 'неприменно' },
    { display: 'непр..одолимый', correct: 'непреодолимый', wrong: 'неприодолимый' },
    { display: 'непр..ходящие', correct: 'непреходящие', wrong: 'неприходящие' },
    { display: 'непр..годный', correct: 'непригодный', wrong: 'непрегодный' },
    { display: 'непр..ступная', correct: 'неприступная', wrong: 'непреступная' },
    { display: 'непр..хотливый', correct: 'неприхотливый', wrong: 'непрехотливый' },
    { display: 'пр..большой', correct: 'пребольшой', wrong: 'прибольшой' },
    { display: 'пр..бывать (в городе)', correct: 'пребывать', wrong: 'прибывать' },
    { display: 'пр..возмочь', correct: 'превозмочь', wrong: 'привозмочь' },
    { display: 'пр..возносить', correct: 'превозносить', wrong: 'привозносить' },
    { display: 'пр..вратное', correct: 'превратное', wrong: 'привратное' },
    { display: 'пр..вращение', correct: 'превращение', wrong: 'привращение' },
    { display: 'пр..высить', correct: 'превысить', wrong: 'привысить' },
    { display: 'пр..града', correct: 'преграда', wrong: 'приграда' },
    { display: 'пр..дания (старины)', correct: 'предания', wrong: 'придания' },
    { display: 'пр..дел (терпению)', correct: 'предел', wrong: 'придел' },
    { display: 'пр..добрый', correct: 'предобрый', wrong: 'придобрый' },
    { display: 'пр..емник (достойный)', correct: 'преемник', wrong: 'приемник' },
    { display: 'пр..дставить', correct: 'представить', wrong: 'придставить' },
    { display: 'пр..забавный', correct: 'презабавный', wrong: 'призабавный' },
    { display: 'пр..емственность', correct: 'преемственность', wrong: 'приемственность' },
    { display: 'пр..интересный', correct: 'преинтересный', wrong: 'приинтересный' },
    { display: 'пр..злой', correct: 'презлой', wrong: 'призлой' },
    { display: 'пр..ломление', correct: 'преломление', wrong: 'приломление' },
    { display: 'пр..кратить', correct: 'прекратить', wrong: 'прикратить' },
    { display: 'пр..мудрый', correct: 'премудрый', wrong: 'примудрый' },
    { display: 'пр..милый', correct: 'премилый', wrong: 'примилый' },
    { display: 'пр..обладать', correct: 'преобладать', wrong: 'приобладать' },
    { display: 'пр..неприятный', correct: 'пренеприятный', wrong: 'принеприятный' },
    { display: 'пр..одоление', correct: 'преодоление', wrong: 'приодоление' },
    { display: 'пр..образовать', correct: 'преобразовать', wrong: 'приобразовать' },
    { display: 'пр..острый', correct: 'преострый', wrong: 'приострый' },
    { display: 'пр..одолеть', correct: 'преодолеть', wrong: 'приодолеть' },
    { display: 'пр..рвать (докладчика)', correct: 'прервать', wrong: 'прирвать' },
    { display: 'пр..рываемый', correct: 'прерываемый', wrong: 'прирываемый' },
    { display: 'пр..светлый', correct: 'пресветлый', wrong: 'присветлый' },
    { display: 'пр..сечь (нарушение)', correct: 'пресечь', wrong: 'присечь' },
    { display: 'пр..следовать', correct: 'преследовать', wrong: 'приследовать' },
    { display: 'пр..спокойный', correct: 'преспокойный', wrong: 'приспокойный' },
    { display: 'пр..старелый', correct: 'престарелый', wrong: 'пристарелый' },
    { display: 'пр..стол', correct: 'престол', wrong: 'пристол' },
    { display: 'пр..ступник', correct: 'преступник', wrong: 'приступник' },
    { display: 'пр..сытиться', correct: 'пресытиться', wrong: 'присытиться' },
    { display: 'пр..творить (в жизнь)', correct: 'претворить', wrong: 'притворить' },
    { display: 'пр..твориться (спящим)', correct: 'притвориться', wrong: 'претвориться' },
    { display: 'пр..терпеть (изменения)', correct: 'претерпеть', wrong: 'притерпеть' },
    { display: 'пр..ткновения (камень)', correct: 'преткновения', wrong: 'приткновения' },
    { display: 'пр..увеличенный', correct: 'преувеличенный', wrong: 'приувеличенный' },
    { display: 'пр..успевающий', correct: 'преуспевающий', wrong: 'приуспевающий' },
    { display: 'пр..амурский', correct: 'приамурский', wrong: 'преамурский' },
    { display: 'пр..бегнуть', correct: 'прибегнуть', wrong: 'пребегнуть' },
    { display: 'пр..брежный', correct: 'прибрежный', wrong: 'пребрежный' },
    { display: 'пр..беречь', correct: 'приберечь', wrong: 'преберечь' },
    { display: 'пр..верженец', correct: 'приверженец', wrong: 'преверженец' },
    { display: 'пр..бывать (в город)', correct: 'прибывать', wrong: 'пребывать' },
    { display: 'пр..вокзальный', correct: 'привокзальный', wrong: 'превокзальный' },
    { display: 'пр..видеться', correct: 'привидеться', wrong: 'превидеться' },
    { display: 'пр..вольные', correct: 'привольные', wrong: 'превольные' },
    { display: 'пр..волжский', correct: 'приволжский', wrong: 'преволжский' },
    { display: 'пр..вязанный', correct: 'привязанный', wrong: 'превязанный' },
    { display: 'пр..встать', correct: 'привстать', wrong: 'превстать' },
    { display: 'пр..говор', correct: 'приговор', wrong: 'преговор' },
    { display: 'пр..глушить', correct: 'приглушить', wrong: 'преглушить' },
    { display: 'пр..горок', correct: 'пригорок', wrong: 'прегорок' },
    { display: 'пр..гожий', correct: 'пригожий', wrong: 'прегожий' },
    { display: 'пр..даваться (размышлениям)', correct: 'придаваться', wrong: 'предаваться' },
    { display: 'пр..давать (значение)', correct: 'придавать', wrong: 'предавать' },
    { display: 'пр..думал', correct: 'придумал', wrong: 'предумал' },
    { display: 'пр..домовая', correct: 'придомовая', wrong: 'предомовая' },
    { display: 'пр..жился', correct: 'прижился', wrong: 'прежился' },
    { display: 'пр..емлемый', correct: 'приемлемый', wrong: 'преемлемый' },
    { display: 'пр..зывающий', correct: 'призывающий', wrong: 'презывающий' },
    { display: 'пр..задумался', correct: 'призадумался', wrong: 'презадумался' },
    { display: 'пр..мкнуть', correct: 'примкнуть', wrong: 'премкнуть' },
    { display: 'пр..людно', correct: 'прилюдно', wrong: 'прелюдно' },
    { display: 'пр..морье', correct: 'приморье', wrong: 'преморье' },
    { display: 'пр..морский', correct: 'приморский', wrong: 'преморский' },
    { display: 'пр..общение', correct: 'приобщение', wrong: 'преобщение' },
    { display: 'пр..ободрился', correct: 'приободрился', wrong: 'преободрился' },
    { display: 'пр..плести', correct: 'приплести', wrong: 'преплести' },
    { display: 'пр..писывать', correct: 'приписывать', wrong: 'преписывать' },
    { display: 'пр..прятать', correct: 'припрятать', wrong: 'препрятать' },
    { display: 'пр..поднять', correct: 'приподнять', wrong: 'преподнять' },
    { display: 'пр..скорбный', correct: 'прискорбный', wrong: 'прескорбный' },
    { display: 'пр..сесть', correct: 'присесть', wrong: 'пресесть' },
    { display: 'пр..смотреться', correct: 'присмотреться', wrong: 'пресмотреться' },
    { display: 'пр..слать', correct: 'прислать', wrong: 'преслать' },
    { display: 'пр..спосабливающийся', correct: 'приспосабливающийся', wrong: 'преспосабливающийся' },
    { display: 'пр..смотром (под)', correct: 'присмотром', wrong: 'пресмотром' },
    { display: 'пр..строиться', correct: 'пристроиться', wrong: 'престроиться' },
    { display: 'пр..стегнуться', correct: 'пристегнуться', wrong: 'престегнуться' },
    { display: 'пр..стыдить', correct: 'пристыдить', wrong: 'престыдить' },
    { display: 'пр..ступить (к делу)', correct: 'приступить', wrong: 'преступить' },
    { display: 'пр..творить (окно)', correct: 'притворить', wrong: 'претворить' },
    { display: 'пр..танцовывать', correct: 'пританцовывать', wrong: 'претанцовывать' },
    { display: 'Пр..уралье', correct: 'Приуралье', wrong: 'Преуралье' },
    { display: 'пр..уныл', correct: 'приуныл', wrong: 'преуныл' },
    { display: 'пр..школьный', correct: 'пришкольный', wrong: 'прешкольный' },
    { display: 'пр..чудливый', correct: 'причудливый', wrong: 'пречудливый' },
    { display: 'пр..ютить', correct: 'приютить', wrong: 'преютить' },
    { display: 'сопр..косновение', correct: 'соприкосновение', wrong: 'сопрекосновение' },
    { display: 'сопр..частность', correct: 'сопричастность', wrong: 'сопречастность' },
  ],
  zs: [
    { display: 'бе..болезненно', correct: 'безболезненно', wrong: 'бесболезненно' },
    { display: 'бе..вкусный', correct: 'безвкусный', wrong: 'бесвкусный' },
    { display: 'бе..донный', correct: 'бездонный', wrong: 'бесдонный' },
    { display: 'бе..жалостность', correct: 'безжалостность', wrong: 'бесжалостность' },
    { display: 'бе..жизненный', correct: 'безжизненный', wrong: 'бесжизненный' },
    { display: 'бе..звёздный', correct: 'беззвёздный', wrong: 'бесзвёздный' },
    { display: 'бе..корыстный', correct: 'бескорыстный', wrong: 'безкорыстный' },
    { display: 'бе..крайний', correct: 'бескрайний', wrong: 'безкрайний' },
    { display: 'бе..кровный', correct: 'бескровный', wrong: 'безкровный' },
    { display: 'бе..печность', correct: 'беспечность', wrong: 'безпечность' },
    { display: 'бе..плановый', correct: 'бесплановый', wrong: 'безплановый' },
    { display: 'бе..правный', correct: 'бесправный', wrong: 'безправный' },
    { display: 'бе..принципный', correct: 'беспринципный', wrong: 'безпринципный' },
    { display: 'бе..пробудный', correct: 'беспробудный', wrong: 'безпробудный' },
    { display: 'бе..проглядный', correct: 'беспроглядный', wrong: 'безпроглядный' },
    { display: 'бе..хитростный', correct: 'бесхитростный', wrong: 'безхитростный' },
    { display: 'бе..цельный', correct: 'бесцельный', wrong: 'безцельный' },
    { display: 'бе..ценный', correct: 'бесценный', wrong: 'безценный' },
    { display: 'бе..человечный', correct: 'бесчеловечный', wrong: 'безчеловечный' },
    { display: 'бе..численный', correct: 'бесчисленный', wrong: 'безчисленный' },
    { display: 'бе..чувственный', correct: 'бесчувственный', wrong: 'безчувственный' },
    { display: 'бе..шовный', correct: 'бесшовный', wrong: 'безшовный' },
    { display: 'бе..шумный', correct: 'бесшумный', wrong: 'безшумный' },
    { display: 'в..бираться', correct: 'взбираться', wrong: 'всбираться' },
    { display: 'в..дремнуть', correct: 'вздремнуть', wrong: 'всдремнуть' },
    { display: 'во..местить', correct: 'возместить', wrong: 'восместить' },
    { display: 'во..кликнуть', correct: 'воскликнуть', wrong: 'возкликнуть' },
    { display: 'во..противиться', correct: 'воспротивиться', wrong: 'возпротивиться' },
    { display: 'в..пугнуть', correct: 'вспугнуть', wrong: 'взпугнуть' },
    { display: 'в..пыхнуть', correct: 'вспыхнуть', wrong: 'взпыхнуть' },
    { display: 'в..тревоженный', correct: 'встревоженный', wrong: 'взтревоженный' },
    { display: 'ди..баланс', correct: 'дисбаланс', wrong: 'дизбаланс' },
    { display: 'и..бавиться', correct: 'избавиться', wrong: 'исбавиться' },
    { display: 'и..брать', correct: 'избрать', wrong: 'исбрать' },
    { display: 'и..виваться', correct: 'извиваться', wrong: 'исвиваться' },
    { display: 'и..гнать', correct: 'изгнать', wrong: 'исгнать' },
    { display: 'и..готовленный', correct: 'изготовленный', wrong: 'исготовленный' },
    { display: 'и..древле', correct: 'издревле', wrong: 'исдревле' },
    { display: 'и..желта-красный', correct: 'изжелта-красный', wrong: 'исжелта-красный' },
    { display: 'и..мельчить', correct: 'измельчить', wrong: 'исмельчить' },
    { display: 'и..рисованный', correct: 'изрисованный', wrong: 'исрисованный' },
    { display: 'и..коверкать', correct: 'исковеркать', wrong: 'изковеркать' },
    { display: 'и..колесить', correct: 'исколесить', wrong: 'изколесить' },
    { display: 'и..печь', correct: 'испечь', wrong: 'изпечь' },
    { display: 'и..подлобья', correct: 'исподлобья', wrong: 'изподлобья' },
    { display: 'и..подтишка', correct: 'исподтишка', wrong: 'изподтишка' },
    { display: 'и..пугаться', correct: 'испугаться', wrong: 'изпугаться' },
    { display: 'и..синя-зелёный', correct: 'иссиня-зелёный', wrong: 'изсиня-зелёный' },
    { display: 'и..точать', correct: 'источать', wrong: 'източать' },
    { display: 'и..ходящий', correct: 'исходящий', wrong: 'изходящий' },
    { display: 'и..чезнуть', correct: 'исчезнуть', wrong: 'изчезнуть' },
    { display: 'и..черпать', correct: 'исчерпать', wrong: 'изчерпать' },
    { display: 'мирово..зрение', correct: 'мировоззрение', wrong: 'мировосзрение' },
    { display: 'не..доровый', correct: 'нездоровый', wrong: 'несдоровый' },
    { display: 'неи..бежный', correct: 'неизбежный', wrong: 'неисбежный' },
    { display: 'неи..сякаемый', correct: 'неиссякаемый', wrong: 'неизсякаемый' },
    { display: 'не..балансированный', correct: 'несбалансированный', wrong: 'незбалансированный' },
    { display: 'не..гибаемый', correct: 'несгибаемый', wrong: 'незгибаемый' },
    { display: 'не..говорчивый', correct: 'несговорчивый', wrong: 'незговорчивый' },
    { display: 'не..гораемый', correct: 'несгораемый', wrong: 'незгораемый' },
    { display: 'не..давленный', correct: 'несдавленный', wrong: 'нездавленный' },
    { display: 'не..держанный', correct: 'несдержанный', wrong: 'нездержанный' },
    { display: 'не..добровать', correct: 'несдобровать', wrong: 'нездобровать' },
    { display: 'не..жатый', correct: 'несжатый', wrong: 'незжатый' },
    { display: 'не..кончаемый', correct: 'нескончаемый', wrong: 'незкончаемый' },
    { display: 'ни..падающий', correct: 'ниспадающий', wrong: 'низпадающий' },
    { display: 'ни..послать', correct: 'ниспослать', wrong: 'низпослать' },
    { display: 'ни..провергать', correct: 'ниспровергать', wrong: 'низпровергать' },
    { display: 'обе..доленный', correct: 'обездоленный', wrong: 'обесдоленный' },
    { display: 'пере..данный', correct: 'пересданный', wrong: 'перезданный' },
    { display: 'ра..брасывать', correct: 'разбрасывать', wrong: 'расбрасывать' },
    { display: 'ра..грызть', correct: 'разгрызть', wrong: 'расгрызть' },
    { display: 'ра..жечь', correct: 'разжечь', wrong: 'расжечь' },
    { display: 'ра..жимать', correct: 'разжимать', wrong: 'расжимать' },
    { display: 'ра..калённый', correct: 'раскалённый', wrong: 'разкалённый' },
    { display: 'ра..каяться', correct: 'раскаяться', wrong: 'разкаяться' },
    { display: 'ра..торгнуть', correct: 'расторгнуть', wrong: 'разторгнуть' },
    { display: 'ра..хаживать', correct: 'расхаживать', wrong: 'разхаживать' },
    { display: 'ра..царапать', correct: 'расцарапать', wrong: 'разцарапать' },
    { display: 'ра..ценки', correct: 'расценки', wrong: 'разценки' },
    { display: 'ра..чертить', correct: 'расчертить', wrong: 'разчертить' },
    { display: 'ра..чётливый', correct: 'расчётливый', wrong: 'разчётливый' },
    { display: 'ра..чудесный', correct: 'расчудесный', wrong: 'разчудесный' },
    { display: 'ра..щедриться', correct: 'расщедриться', wrong: 'разщедриться' },
    { display: 'ро..черк', correct: 'росчерк', wrong: 'розчерк' },
    { display: '..бивчивый', correct: 'сбивчивый', wrong: 'збивчивый' },
    { display: '..горевший', correct: 'сгоревший', wrong: 'згоревший' },
    { display: '..держал', correct: 'сдержал', wrong: 'здержал' },
    { display: '..жать', correct: 'сжать', wrong: 'зжать' },
    { display: 'сни..хождение', correct: 'снисхождение', wrong: 'снизхождение' },
    { display: 'чере..строчный', correct: 'чересстрочный', wrong: 'черезстрочный' },
    { display: 'чере..чур', correct: 'чересчур', wrong: 'черезчур' },
    { display: 'чре..вычайно', correct: 'чрезвычайно', wrong: 'чресвычайно' },
    { display: 'чре..вычайный', correct: 'чрезвычайный', wrong: 'чресвычайный' },
    { display: 'чре..мерный', correct: 'чрезмерный', wrong: 'чресмерный' },
  ],
  iy: [
    { display: 'без..дейный', correct: 'безыдейный', wrong: 'безидейный' },
    { display: 'без..мянный', correct: 'безымянный', wrong: 'безимянный' },
    { display: 'без..нвентарный', correct: 'безынвентарный', wrong: 'безинвентарный' },
    { display: 'без..нициативный', correct: 'безынициативный', wrong: 'безинициативный' },
    { display: 'без..скусный', correct: 'безыскусный', wrong: 'безискусный' },
    { display: 'без..сходный', correct: 'безысходный', wrong: 'безисходный' },
    { display: 'вз..мание', correct: 'взимание', wrong: 'взымание' },
    { display: 'вз..мать', correct: 'взимать', wrong: 'взымать' },
    { display: 'вз..скать', correct: 'взыскать', wrong: 'взискать' },
    { display: 'дез..нфекция', correct: 'дезинфекция', wrong: 'дезынфекция' },
    { display: 'дез..нформация', correct: 'дезинформация', wrong: 'дезынформация' },
    { display: 'за..нтересованный', correct: 'заинтересованный', wrong: 'заынтересованный' },
    { display: 'из..мать', correct: 'изымать', wrong: 'изимать' },
    { display: 'из..скать', correct: 'изыскать', wrong: 'изискать' },
    { display: 'контр..гра', correct: 'контригра', wrong: 'контрыгра' },
    { display: 'мед..нститут', correct: 'мединститут', wrong: 'медынститут' },
    { display: 'меж..гровой', correct: 'межигровой', wrong: 'межыгровой' },
    { display: 'меж..здательский', correct: 'межиздательский', wrong: 'межыздательский' },
    { display: 'меж..нститутский', correct: 'межинститутский', wrong: 'межынститутский' },
    { display: 'меж..нтернатский', correct: 'межинтернатский', wrong: 'межынтернатский' },
    { display: 'на..граться', correct: 'наиграться', wrong: 'наыграться' },
    { display: 'небез..нтересный', correct: 'небезынтересный', wrong: 'небезинтересный' },
    { display: 'об..грать', correct: 'обыграть', wrong: 'обиграть' },
    { display: 'об..ск', correct: 'обыск', wrong: 'обиск' },
    { display: 'от..скать', correct: 'отыскать', wrong: 'отискать' },
    { display: 'под..грать', correct: 'подыграть', wrong: 'подиграть' },
    { display: 'под..скать', correct: 'подыскать', wrong: 'подискать' },
    { display: 'под..тожить', correct: 'подытожить', wrong: 'подитожить' },
    { display: 'по..скать', correct: 'поискать', wrong: 'поыскать' },
    { display: 'пост..мпрессионизм', correct: 'постимпрессионизм', wrong: 'постымпрессионизм' },
    { display: 'пост..ндустриальный', correct: 'постиндустриальный', wrong: 'постындустриальный' },
    { display: 'пред..дущий', correct: 'предыдущий', wrong: 'предидущий' },
    { display: 'пред..нфарктный', correct: 'предынфарктный', wrong: 'прединфарктный' },
    { display: 'пред..стория', correct: 'предыстория', wrong: 'предистория' },
    { display: 'пред..юньский', correct: 'предыюньский', wrong: 'предиюньский' },
    { display: 'про..грать', correct: 'проиграть', wrong: 'проыграть' },
    { display: 'раз..гранный', correct: 'разыгранный', wrong: 'разигранный' },
    { display: 'раз..скать', correct: 'разыскать', wrong: 'разискать' },
    { display: 'раз..щут', correct: 'разыщут', wrong: 'разищут' },
    { display: 'роз..грыш', correct: 'розыгрыш', wrong: 'розигрыш' },
    { display: 'роз..ск', correct: 'розыск', wrong: 'розиск' },
    { display: 'сверх..дейный', correct: 'сверхидейный', wrong: 'сверхыдейный' },
    { display: 'сверх..дея', correct: 'сверхидея', wrong: 'сверхыдея' },
    { display: 'сверх..зысканный', correct: 'сверхизысканный', wrong: 'сверхызысканный' },
    { display: 'сверх..зящный', correct: 'сверхизящный', wrong: 'сверхызящный' },
    { display: 'сверх..нвестиции', correct: 'сверхинвестиции', wrong: 'сверхынвестиции' },
    { display: 'сверх..скусный', correct: 'сверхискусный', wrong: 'сверхыскусный' },
    { display: 'супер..гра', correct: 'суперигра', wrong: 'суперыгра' },
    { display: 'с..грать', correct: 'сыграть', wrong: 'сиграть' },
    { display: 'с..змала', correct: 'сызмала', wrong: 'сизмала' },
    { display: 'с..знова', correct: 'сызнова', wrong: 'сизнова' },
    { display: 'с..митировать', correct: 'сымитировать', wrong: 'симитировать' },
    { display: 'с..мпровизировать', correct: 'сымпровизировать', wrong: 'симпровизировать' },
    { display: 'транс..ранский', correct: 'трансиранский', wrong: 'трансыранский' },
    { display: 'трех..мпульсный', correct: 'трехимпульсный', wrong: 'трехымпульсный' },
    { display: 'фин..нспектор', correct: 'фининспектор', wrong: 'финынспектор' },
  ],
  yer: [
    { display: 'ад..ютант', correct: 'адъютант', wrong: 'адьютант' },
    { display: 'бар..ерный', correct: 'барьерный', wrong: 'баръерный' },
    { display: 'без..ядерный', correct: 'безъядерный', wrong: 'безьядерный' },
    { display: 'без..языкий', correct: 'безъязыкий', wrong: 'безьязыкий' },
    { display: 'бур..ян', correct: 'бурьян', wrong: 'буръян' },
    { display: 'вз..ерошить', correct: 'взъерошить', wrong: 'взьерошить' },
    { display: 'волеиз..явление', correct: 'волеизъявление', wrong: 'волеизьявление' },
    { display: 'в..едливый', correct: 'въедливый', wrong: 'вьедливый' },
    { display: 'в..езжать', correct: 'въезжать', wrong: 'вьезжать' },
    { display: 'в..ётся', correct: 'вьётся', wrong: 'въётся' },
    { display: 'в..явь', correct: 'въявь', wrong: 'вьявь' },
    { display: 'гидропод..ёмник', correct: 'гидроподъёмник', wrong: 'гидроподьёмник' },
    { display: 'двух..ядерный', correct: 'двухъядерный', wrong: 'двухьядерный' },
    { display: 'двух..ярусный', correct: 'двухъярусный', wrong: 'двухьярусный' },
    { display: 'зав..южило', correct: 'завьюжило', wrong: 'завъюжило' },
    { display: 'из..ездить', correct: 'изъездить', wrong: 'изьездить' },
    { display: 'из..ян', correct: 'изъян', wrong: 'изьян' },
    { display: 'из..ять', correct: 'изъять', wrong: 'изьять' },
    { display: 'интерв..юировать', correct: 'интервьюировать', wrong: 'интервъюировать' },
    { display: 'интер..ер', correct: 'интерьер', wrong: 'интеръер' },
    { display: 'квартирос..ёмщик', correct: 'квартиросъёмщик', wrong: 'квартиросьёмщик' },
    { display: 'кинос..ёмка', correct: 'киносъёмка', wrong: 'киносьёмка' },
    { display: 'комп..ютер', correct: 'компьютер', wrong: 'компъютер' },
    { display: 'кур..ер', correct: 'курьер', wrong: 'куръер' },
    { display: 'меж..языковой', correct: 'межъязыковой', wrong: 'межьязыковой' },
    { display: 'необ..езженный', correct: 'необъезженный', wrong: 'необьезженный' },
    { display: 'необ..ятный', correct: 'необъятный', wrong: 'необьятный' },
    { display: 'неот..емлемый', correct: 'неотъемлемый', wrong: 'неотьемлемый' },
    { display: 'обез..яний', correct: 'обезьяний', wrong: 'обезъяний' },
    { display: 'об..ект', correct: 'объект', wrong: 'обьект' },
    { display: 'об..ёмный', correct: 'объёмный', wrong: 'обьёмный' },
    { display: 'об..яснение', correct: 'объяснение', wrong: 'обьяснение' },
    { display: 'об..ятия', correct: 'объятия', wrong: 'обьятия' },
    { display: 'от..единить', correct: 'отъединить', wrong: 'отьединить' },
    { display: 'от..явленный', correct: 'отъявленный', wrong: 'отьявленный' },
    { display: 'пас..янс', correct: 'пасьянс', wrong: 'пасъянс' },
    { display: 'под..езд', correct: 'подъезд', wrong: 'подьезд' },
    { display: 'под..язычный', correct: 'подъязычный', wrong: 'подьязычный' },
    { display: 'порт..ера', correct: 'портьера', wrong: 'портъера' },
    { display: 'почтал..он', correct: 'почтальон', wrong: 'почталъон' },
    { display: 'пред..юбилейный', correct: 'предъюбилейный', wrong: 'предьюбилейный' },
    { display: 'п..едестал', correct: 'пьедестал', wrong: 'пъедестал' },
    { display: 'п..янящий', correct: 'пьянящий', wrong: 'пъянящий' },
    { display: 'раз..единить', correct: 'разъединить', wrong: 'разьединить' },
    { display: 'раз..ехаться', correct: 'разъехаться', wrong: 'разьехаться' },
    { display: 'р..яный', correct: 'рьяный', wrong: 'ръяный' },
    { display: 'сверх..ёмкий', correct: 'сверхъёмкий', wrong: 'сверхьёмкий' },
    { display: 'сверх..естественный', correct: 'сверхъестественный', wrong: 'сверхьестественный' },
    { display: 'соб..ётся', correct: 'собьётся', wrong: 'собъётся' },
    { display: 'сош..ют', correct: 'сошьют', wrong: 'сошъют' },
    { display: 'суб..ективный', correct: 'субъективный', wrong: 'субьективный' },
    { display: 'супер..яркий', correct: 'суперъяркий', wrong: 'суперьяркий' },
    { display: 'с..еденный', correct: 'съеденный', wrong: 'сьеденный' },
    { display: 'с..едобный', correct: 'съедобный', wrong: 'сьедобный' },
    { display: 'с..ёжиться', correct: 'съёжиться', wrong: 'сьёжиться' },
    { display: 'с..езд', correct: 'съезд', wrong: 'сьезд' },
    { display: 'с..ёмка', correct: 'съёмка', wrong: 'сьёмка' },
    { display: 'с..естной', correct: 'съестной', wrong: 'сьестной' },
    { display: 'с..язвить', correct: 'съязвить', wrong: 'сьязвить' },
    { display: 'трех..язычный', correct: 'трехъязычный', wrong: 'трехьязычный' },
    { display: 'фел..етонный', correct: 'фельетонный', wrong: 'фелъетонный' },
    { display: 'фотооб..ектив', correct: 'фотообъектив', wrong: 'фотообьектив' },
  ],
};

export function getPrefixPool(category: PrefixCategory): PrefixItem[] {
  if (category === 'mixed') {
    return [
      ...PREFIX_DATA.unchanged,
      ...PREFIX_DATA.preEpri,
      ...PREFIX_DATA.zs,
      ...PREFIX_DATA.iy,
      ...PREFIX_DATA.yer,
    ];
  }
  return PREFIX_DATA[category];
}
