import LetterInputExercise, { type TextItem } from './LetterInputExercise';

const ITEMS: TextItem[] = [
  { display: 'с_стем_тизировать',          answer: 'систематизировать' },
  { display: 'укр_щать',                   answer: 'укрощать' },
  { display: 'ум_лять значение',           answer: 'умалять' },
  { display: 'разр_дить морковь',          answer: 'разредить' },
  { display: 'ц_лл_фановый',              answer: 'целлофановый' },
  { display: 'непост_жимый',              answer: 'непостижимый' },
  { display: 'п_л_садник',               answer: 'палисадник' },
  { display: 'к_рдинальный',             answer: 'кардинальный' },
  { display: 'пр_стижный',               answer: 'престижный' },
  { display: 'страшное прив_дение',       answer: 'привидение' },
  { display: 'п_р_ферия',                answer: 'периферия' },
  { display: 'м_ц_нат',                  answer: 'меценат' },
  { display: 'д_р_ктива',                answer: 'директива' },
  { display: 'спл_титься',               answer: 'сплотиться' },
  { display: 'обр_мление',               answer: 'обрамление' },
  { display: 'московский ст_рожил',      answer: 'старожил' },
  { display: 'д_л_катес',               answer: 'деликатес' },
  { display: 'д_л_гированный',          answer: 'делегированный' },
  { display: 'аб_туриент',              answer: 'абитуриент' },
  { display: 'нав_вать воспоминания',   answer: 'навевать' },
  { display: 'р_гламент',               answer: 'регламент' },
  { display: 'просв_щение',             answer: 'просвещение' },
  { display: 'посв_щение',              answer: 'посвящение' },
  { display: 'ап_лляция',               answer: 'апелляция' },
  { display: 'претв_рить в жизнь',      answer: 'претворить' },
  { display: 'эт_кетка',                answer: 'этикетка' },
  { display: 'прет_ндовать',            answer: 'претендовать' },
  { display: 'обог_щение',              answer: 'обогащение' },
  { display: 'к_нфорка',               answer: 'конфорка' },
  { display: 'в_рсистый',              answer: 'ворсистый' },
  { display: 'одр_хлевший',            answer: 'одряхлевший' },
  { display: 'асп_рантура',            answer: 'аспирантура' },
  { display: 'аф_ристичный',           answer: 'афористичный' },
  { display: 'ав_нтюра',               answer: 'авантюра' },
  { display: 'ор_нжерея',              answer: 'оранжерея' },
  { display: 'разр_дить обстановку',   answer: 'разрядить' },
  { display: 'аккл_матизация',         answer: 'акклиматизация' },
  { display: 'от_ждествление',         answer: 'отождествление' },
  { display: 'проп_ганда',             answer: 'пропаганда' },
  { display: 'энц_клопедист',          answer: 'энциклопедист' },
  { display: 'ур_вновешенный',         answer: 'уравновешенный' },
  { display: 'ув_дание',               answer: 'увядание' },
  { display: 'г_потетический',         answer: 'гипотетический' },
  { display: 'инт_лл_ктуальный',      answer: 'интеллектуальный' },
  { display: 'к_рифей',               answer: 'корифей' },
  { display: 'дельфин к_сатка',        answer: 'косатка' },
  { display: 'птица к_сатка',          answer: 'касатка' },
  { display: 'п_сс_мист',             answer: 'пессимист' },
  { display: 'п_р_доксальный',        answer: 'парадоксальный' },
  { display: 'пр_ц_дент',             answer: 'прецедент' },
  { display: 'сув_р_нитет',           answer: 'суверенитет' },
  { display: 'эст_када',              answer: 'эстакада' },
  // ─── Различай корни (по смыслу) ─────────────────────────────────────────
  { display: 'ст_рожил склад',                  answer: 'сторожил' },
  { display: 'ум_лять о пощаде',                answer: 'умолять' },
  { display: 'просл_влять героя',               answer: 'прославлять' },
  { display: 'благосл_вить на подвиг',          answer: 'благословить' },
  { display: 'раздр_жать своим поведением',     answer: 'раздражать' },
  { display: 'задр_жать от холода',             answer: 'задрожать' },
  { display: 'пок_рать врага',                  answer: 'покарать' },
  { display: 'пок_рить природу',                answer: 'покорить' },
  { display: 'ук_рять за лень',                 answer: 'укорять' },
  { display: 'разр_дить ружьё',                 answer: 'разрядить' },
  { display: 'посв_тить свечой',                answer: 'посветить' },
  { display: 'посв_тить стихотворение другу',   answer: 'посвятить' },
  { display: 'прист_жной воротник',             answer: 'пристежной' },
  { display: 'прист_жная лошадь',               answer: 'пристяжная' },
  { display: 'флаг разв_вается на ветру',       answer: 'развевается' },
  { display: 'ребёнок разв_вается успешно',     answer: 'развивается' },
  { display: 'нав_вать локоны',                 answer: 'навивать' },
  { display: 'ут_шать малыша',                  answer: 'утешать' },
  { display: 'ут_хать постепенно',              answer: 'утихать' },
  { display: 'прим_рять пальто',                answer: 'примерять' },
  { display: 'прим_рить врагов',                answer: 'примирить' },
  { display: 'скр_пя сердце',                   answer: 'скрепя' },
  { display: 'скр_петь стулом',                 answer: 'скрипеть' },
  { display: 'ув_дать издали',                  answer: 'увидать' },
  { display: 'ув_дать без влаги',               answer: 'увядать' },
  // ─── Словарные слова: безударные гласные ─────────────────────────────────
  { display: 'инт_лл_кт',              answer: 'интеллект' },
  { display: 'р_ц_нзент',              answer: 'рецензент' },
  { display: 'ст_р_отип',              answer: 'стереотип' },
  { display: 'през_нтация',           answer: 'презентация' },
  { display: 'опт_м_стичный',         answer: 'оптимистичный' },
  { display: 'прив_легия',            answer: 'привилегия' },
  { display: 'прим_тивный',           answer: 'примитивный' },
  { display: 'избирательная к_мпания',    answer: 'кампания' },
  { display: 'к_мпания друзей',           answer: 'компания' },
  { display: 'к_такомба',             answer: 'катакомба' },
  { display: 'к_мп_нент',             answer: 'компонент' },
  { display: 'к_л_ссальный',          answer: 'колоссальный' },
  { display: 'гром_здкий',            answer: 'громоздкий' },
  { display: 'пров_цировать',         answer: 'провоцировать' },
  { display: 'инт_лл_гентный',        answer: 'интеллигентный' },
  { display: 'в_ст_бюль',             answer: 'вестибюль' },
  { display: 'р_з_денция',            answer: 'резиденция' },
  { display: 'с_м_нар',               answer: 'семинар' },
  { display: 'пол_миз_ровать',        answer: 'полемизировать' },
  { display: 'эксп_р_мент',           answer: 'эксперимент' },
  { display: 'в_н_грет',              answer: 'винегрет' },
  { display: 'д_л_тант',              answer: 'дилетант' },
  { display: 'ор__нтация',            answer: 'ориентация' },
  { display: 'д_сп_тчер',             answer: 'диспетчер' },
  { display: 'к_ординация',           answer: 'координация' },
  { display: 'об_няние',              answer: 'обоняние' },
  { display: 'ар_мат',                answer: 'аромат' },
  { display: 'об_яние',               answer: 'обаяние' },
  { display: 'р_ставрация',           answer: 'реставрация' },
  { display: 'про_браз',              answer: 'прообраз' },
  { display: 'д_кламировать',         answer: 'декламировать' },
  { display: 'пан_рама',              answer: 'панорама' },
  { display: 'бюлл_тень',             answer: 'бюллетень' },
  { display: 'кан_тель',              answer: 'канитель' },
  { display: 'кан_нада',              answer: 'канонада' },
  { display: 'комп_тентный',          answer: 'компетентный' },
  { display: 'пол_мика',              answer: 'полемика' },
  { display: 'симп_тичный',           answer: 'симпатичный' },
  { display: 'впеч_тлительный',       answer: 'впечатлительный' },
  { display: 'экстр_мальный',         answer: 'экстремальный' },
  { display: 'недос_гаемый',          answer: 'недосягаемый' },
  { display: 'ош_ломительный',        answer: 'ошеломительный' },
  { display: 'ди_пазон',              answer: 'диапазон' },
  { display: 'мор_торий',             answer: 'мораторий' },
  { display: 'д_легат',               answer: 'делегат' },
];

interface Props {
  onBack: () => void;
}

export default function RootSpelling({ onBack }: Props) {
  return (
    <LetterInputExercise
      items={ITEMS}
      resultKey="root-spelling"
      title="Правописание корней"
      emoji="🔠"
      subtitle="Введите пропущенные буквы"
      onBack={onBack}
    />
  );
}
