import type { Exercise } from './types';

export const RUSSIAN_EXERCISES: Exercise[] = [
  {
    id: 'adverbs',
    title: 'Правописание наречий',
    description: 'Выберите правильное написание: слитно или раздельно. Тренирует грамотность и готовит к ЕГЭ по русскому языку.',
    icon: '📝',
    color: 'text-indigo-700',
    gradient: 'from-indigo-500 to-blue-600',
  },
  {
    id: 'prefixes',
    title: 'Правописание приставок',
    description: 'Выберите правильную букву на месте пропуска. Тренирует знание приставок и готовит к ЕГЭ.',
    icon: '✍️',
    color: 'text-indigo-700',
    gradient: 'from-indigo-500 to-blue-600',
  },
  {
    id: 'spelling-nn',
    title: 'Правописание Н и НН',
    description: 'Сколько Н нужно вставить на месте пропуска? Тренирует орфографию и готовит к ЕГЭ.',
    icon: '✏️',
    color: 'text-indigo-700',
    gradient: 'from-indigo-500 to-blue-600',
  },
  {
    id: 'word-forms',
    title: 'Формы слова',
    description: 'Выберите правильную форму множественного числа. Тренирует грамматическую норму.',
    icon: '📚',
    color: 'text-indigo-700',
    gradient: 'from-indigo-500 to-blue-600',
  },
  {
    id: 'stress',
    title: 'Ударение',
    description: 'Выберите слово с правильным ударением. Тренирует орфоэпическую норму русского языка.',
    icon: '🔊',
    color: 'text-indigo-700',
    gradient: 'from-indigo-500 to-blue-600',
  },
];

export const EXERCISES: Exercise[] = [
  {
    id: 'munsterberg',
    title: 'Тест Мюнстерберга',
    description: 'Найдите спрятанные слова в строке случайных букв. Тренирует концентрацию и избирательность внимания.',
    icon: '🔍',
    color: 'text-violet-600',
    gradient: 'from-violet-400 to-purple-500',
  },
  {
    id: 'philwords',
    title: 'Филворды',
    description: 'Найдите все слова в сетке букв: горизонтально, вертикально, по диагонали. Тренирует внимание и словарный запас.',
    icon: '📝',
    color: 'text-blue-600',
    gradient: 'from-blue-400 to-cyan-500',
  },
  {
    id: 'schulte',
    title: 'Таблица Шульте',
    description: 'Кликайте числа по порядку от 1 до 25. Тренирует скорость восприятия и переключение внимания.',
    icon: '🔢',
    color: 'text-indigo-600',
    gradient: 'from-indigo-400 to-blue-500',
  },
  {
    id: 'sequence',
    title: 'Последовательности',
    description: 'Запомните последовательность чисел или слов и воспроизведите её. Тренирует кратковременную память.',
    icon: '🧠',
    color: 'text-lime-600',
    gradient: 'from-lime-400 to-green-500',
  },
  {
    id: 'pairs',
    title: 'Игра на пары',
    description: 'Запомните расположение карточек и найдите все совпадающие пары. Тренирует зрительную память.',
    icon: '🃏',
    color: 'text-orange-600',
    gradient: 'from-orange-400 to-amber-500',
  },
  {
    id: 'balls',
    title: 'Шарики с номерами',
    description: 'Запомните номера шариков и нажимайте их по порядку после того, как цифры спрячутся. Тренирует память и внимание.',
    icon: '🎯',
    color: 'text-emerald-600',
    gradient: 'from-emerald-400 to-teal-500',
  },
  {
    id: 'reaction',
    title: 'Реакция на шарик',
    description: 'Кликайте по шарику до того, как он улетит за край. Тренирует скорость реакции и концентрацию.',
    icon: '⚡',
    color: 'text-red-600',
    gradient: 'from-red-400 to-pink-500',
  },
];
